# This file generates the GitHub Actions matrix for Corne with E-Paper display.
#
---
include:
  - board: nice_nano_v2
    shield: corne_left
  - board: nice_nano_v2
    shield: corne_right
  - board: nice_nano_v2
    shield: settings_reset
