# This file generates the GitHub Actions matrix
#
---
include:
  - board: nice_nano_v2
    shield: corne_left corne_epaper
    artifact-name: corne_epaper_left_test
  - board: nice_nano_v2
    shield: corne_right corne_epaper
    artifact-name: corne_epaper_right_test
  - board: nice_nano_v2
    shield: settings_reset
