# Enable ZMK Display for E-Paper screen
CONFIG_ZMK_DISPLAY=y

# Increase Bluetooth transmit power (+8dBm) for 52840NANO Veto
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Eager debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=7

# Power Management & Sleep
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
